apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: abhishekf5/ultimate-cicd:replaceImageTag
        ports:
        - containerPort: 8080
---               
apiVersion: v1
kind: Service
metadata:
  labels:
    name: spring-boot-app
  name: spring-boot-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: spring-boot-app
